# Site settings
title: تورماھىرى بىلوگى
email: ttormahiri@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
 تورماھىرى كۆچمە ئۈسكۈنىلەرگ ئەپ ئاچقۇچى،توربىكەت لايھىەلىگۈچى.
baseurl: /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

github_username:  tormahiri

# Build settings
markdown: kramdown
